package uk.gov.ons.ctp.common.state;

/**
 * Dummy event for test
 */
public enum TestEvent {
  REQUEST_DISTRIBUTED, REQUEST_FAILED, REQUEST_ACCEPTED, REQUEST_COMPLETED, REQUEST_CANCELLED,
  CANCELLATION_DISTRIBUTED, CANCELLATION_FAILED, CANCELLATION_ACCEPTED, CANCELLATION_COMPLETED
}
